version: "0.1"
services:
  spring-boot:
    image: ikm-demo
    build:
      context: .
    ports:
      - "7890:7890"
      - "5005:5005"
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
      - ${MAVEN_SETTINGS_FOLDER}:/root/.m2